### ISSUE TITLE
ios conference vp9 stream will be frozen after publish more than one minutes

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#198] opened 2019-09-16 06:29 UTC

**Comment by jianjunz** [comment] 2019-09-19 10:58
Please try the release build. It usually has better performance than debug build. I tried VP9 with P2P loopback app, video quality is acceptable.

**Comment by JinChengShi** [comment] 2019-10-11 02:32
Release mode also have this issue in conference mode.

**Comment by jianjunz** [comment] 2019-10-11 10:07
Cannot reproduce this issue against server Dec.8 CentOS nightly build.

**Comment by taste1981** [comment] 2019-10-12 09:09
Please also note if this is related to #194.

**Comment by jianjunz** [comment] 2019-10-12 15:17
Closing this issue because it cannot be reproduced against CentOS server, and @taste1981's fix https://github.com/open-webrtc-toolkit/owt-server/pull/310 may potentially fix VP9 video freeze issue. Feel free to reopen this issue if it still exists.

**Closed by jianjunz** 2019-10-12 15:17 UTC
Labels: iOS, needs more info
