### ISSUE TITLE
ios build error on master branch

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#208] opened 2019-09-25 02:29 UTC
[3/331] CXX obj/third_party/webrtc/modules/pacing/pacing/round_robin_packet_queue.o
FAILED: obj/third_party/webrtc/modules/pacing/pacing/round_robin_packet_queue.o 
clang++ -MMD -MF obj/third_party/webrtc/modules/pacing/pacing/round_robin_packet_queue.o.d -DV8_DEPRECATION_WARNINGS -DNO_TCMALLOC -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_LIBCPP_HIDE_FROM_ABI=_LIBCPP_HIDDEN\ _LIBCPP_ALWAYS_INLINE -DCR_XCODE_VERSION=1100 -DCR_CLANG_REVISION=\"338452-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DWEBRTC_ENABLE_PROTOBUF=1 -DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DHAVE_SCTP -DUSE_BUILTIN_SW_CODECS -DHAVE_WEBRTC_VIDEO -DHAVE_WEBRTC_VOICE -DLOGGING_INSIDE_WEBRTC -DWEBRTC_ARCH_ARM64 -DWEBRTC_HAS_NEON -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=1 -DGTEST_RELATIVE_PATH -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_MAC -DWEBRTC_IOS -DABSL_ALLOCATOR_NOTHROW=1 -I../.. -Igen -I../../third_party/webrtc_overrides -I../../third_party/webrtc -I../../third_party/abseil-cpp -I../../third_party/libyuv/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fcolor-diagnostics -fmerge-all-constants -no-canonical-prefixes -arch arm64 -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wunguarded-availability -Wundeclared-selector -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-user-defined-warnings -Wno-unused-lambda-capture -Wno-null-pointer-arithmetic -O0 -fno-omit-frame-pointer -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk -stdlib=libc++ -miphoneos-version-min=9.0 -fembed-bitcode-marker -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wc++11-narrowing -Wimplicit-fallthrough -Wthread-safety -Winconsistent-missing-override -Wundef -fvisibility=default -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++14 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -Wnon-virtual-dtor -Woverloaded-virtual -c ../../third_party/webrtc/modules/pacing/round_robin_packet_queue.cc -o obj/third_party/webrtc/modules/pacing/pacing/round_robin_packet_queue.o
In file included from ../../third_party/webrtc/modules/pacing/round_robin_packet_queue.cc:11:
../../third_party/webrtc/modules/pacing/round_robin_packet_queue.h:46:5: error: explicitly defaulted default constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
    StreamPrioKey() = default;
    ^
../../third_party/webrtc/modules/pacing/round_robin_packet_queue.h:56:37: note: default constructor of 'StreamPrioKey' is implicitly deleted because field 'priority' of const-qualified type 'const RtpPacketSender::Priority' would not be initialized
    const RtpPacketSender::Priority priority;
                                    ^
1 error generated.
[4/331] CXX obj/third_party/webrtc/modules/pacing/pacing/paced_sender.o
FAILED: obj/third_party/webrtc/modules/pacing/pacing/paced_sender.o 
clang++ -MMD -MF obj/third_party/webrtc/modules/pacing/pacing/paced_sender.o.d -DV8_DEPRECATION_WARNINGS -DNO_TCMALLOC -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_LIBCPP_HIDE_FROM_ABI=_LIBCPP_HIDDEN\ _LIBCPP_ALWAYS_INLINE -DCR_XCODE_VERSION=1100 -DCR_CLANG_REVISION=\"338452-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DWEBRTC_ENABLE_PROTOBUF=1 -DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DHAVE_SCTP -DUSE_BUILTIN_SW_CODECS -DHAVE_WEBRTC_VIDEO -DHAVE_WEBRTC_VOICE -DLOGGING_INSIDE_WEBRTC -DWEBRTC_ARCH_ARM64 -DWEBRTC_HAS_NEON -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=1 -DGTEST_RELATIVE_PATH -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_MAC -DWEBRTC_IOS -DABSL_ALLOCATOR_NOTHROW=1 -I../.. -Igen -I../../third_party/webrtc_overrides -I../../third_party/webrtc -I../../third_party/abseil-cpp -I../../third_party/libyuv/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fcolor-diagnostics -fmerge-all-constants -no-canonical-prefixes -arch arm64 -Wall -Werror -Wextra -Wimplicit-fallthrough -Wthread-safety -Wunguarded-availability -Wundeclared-selector -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-user-defined-warnings -Wno-unused-lambda-capture -Wno-null-pointer-arithmetic -O0 -fno-omit-frame-pointer -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk -stdlib=libc++ -miphoneos-version-min=9.0 -fembed-bitcode-marker -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wc++11-narrowing -Wimplicit-fallthrough -Wthread-safety -Winconsistent-missing-override -Wundef -fvisibility=default -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++14 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -Wnon-virtual-dtor -Woverloaded-virtual -c ../../third_party/webrtc/modules/pacing/paced_sender.cc -o obj/third_party/webrtc/modules/pacing/pacing/paced_sender.o
In file included from ../../third_party/webrtc/modules/pacing/paced_sender.cc:25:
../../third_party/webrtc/modules/pacing/round_robin_packet_queue.h:46:5: error: explicitly defaulted default constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
    StreamPrioKey() = default;
    ^
../../third_party/webrtc/modules/pacing/round_robin_packet_queue.h:56:37: note: default constructor of 'StreamPrioKey' is implicitly deleted because field 'priority' of const-qualified type 'const RtpPacketSender::Priority' would not be initialized
    const RtpPacketSender::Priority priority;
                                    ^
1 error generated.
[8/331] CXX clang_x64/obj/third_party/protobuf/protoc_lib/csharp_message_field.o
ninja: build stopped: subcommand failed.

**Comment by jianjunz** [comment] 2019-09-27 13:02
@taste1981 is it ready to merge 76 to master branch? I think we don't have resources to actively maintain two branches for iOS at the same time.

**Comment by HuaChunbo** [comment] 2019-10-09 07:06
Close it if the issue is gone.

**Comment by jianjunz** [comment] 2019-10-09 14:04
76 branch has been merged to master. I think this issue has been fixed.

**Closed by jianjunz** 2019-10-09 14:04 UTC
