### ISSUE TITLE
ios subscribe the forward stream with h265 codec will lead mcu cannot do any other operation 

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-native#60] opened 2019-03-18 06:35 UTC
1. ios login and publish VP8 codec stream to mcu
2. windows login and publish VP8 codec stream to mcu
3. windows subscribe ios stream with h264 codec
4. ios subscribe windows stream with h265 codec

after step 4, mcu cannot do any other operation even just login

**Comment by yanbin7** [comment] 2019-03-21 06:04
Close the issue . This issue is caused by MCU consume resources e.g CPU etc at server machine.

**Closed by yanbin7** 2019-03-21 06:04 UTC
